create table users (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    created_at timestamp not null
);

create table posts (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    content varchar(2000) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_posts_user
        foreign key (user_id) references users(id)
);
create index idx_posts_user_created on posts (user_id, created_at desc);

create table follows (
    id bigint generated by default as identity primary key,
    follower_id bigint not null,
    followee_id bigint not null,
    created_at timestamp not null,
    constraint fk_follows_follower
        foreign key (follower_id) references users(id),
    constraint fk_follows_followee
        foreign key (followee_id) references users(id),
    constraint uk_follows_pair unique (follower_id, followee_id)
);
create index idx_follows_followee on follows (followee_id);

create table comments (
    id bigint generated by default as identity primary key,
    post_id bigint not null,
    user_id bigint not null,
    content varchar(2000) not null,
    created_at timestamp not null,
    constraint fk_comments_post
        foreign key (post_id) references posts(id),
    constraint fk_comments_user
        foreign key (user_id) references users(id)
);
create index idx_comments_post_created on comments (post_id, created_at desc);
